# Generated by Django 5.2.7 on 2025-11-12 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('Luz', 'Luz (Chilquinta)'), ('Agua', 'Agua (Esval)')], help_text='Selecciona el tipo de servicio de la boleta', max_length=10)),
                ('archivo_boleta', models.FileField(help_text='Sube el archivo PDF de tu boleta', upload_to='boletas/')),
                ('monto', models.IntegerField(blank=True, help_text='(Se extraerá automáticamente del PDF)', null=True)),
                ('consumo', models.DecimalField(blank=True, decimal_places=2, help_text='(Consumo KWh o m³. Se extraerá automáticamente)', max_digits=10, null=True)),
                ('fecha_emision', models.DateField(blank=True, help_text='(Fecha de emisión. Se extraerá automáticamente)', null=True)),
                ('estado_procesamiento', models.CharField(choices=[('PENDIENTE', 'Pendiente de Procesar'), ('PROCESADO', 'Procesado Exitosamente'), ('ERROR', 'Error al Procesar')], default='PENDIENTE', help_text='Estado del procesamiento automático del PDF', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se subió el registro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
